all: $(DXE_NAME) check_exports

clean distclean:
	rm -rf *.DXE *.d *.o *.undef

%.o: %.c
	$(CC) -o $@ -c $(CFLAGS) $(DXE_CFLAGS) $<

%.DXE: %.o $(DXE_FILES)
	$(DXE3GEN) -o $@ $^ $(DXE_LDFLAGS) -U -E _init_ -E _shutdown_ -V | tee $(basename $@).undef | sort
	cp $@ ..

check_exports: $(DXE_NAME) ../$(DXE_TEMPLATE)
	python3 ../check_exports.py ../$(DXE_TEMPLATE) $(basename $<).undef
