#
# GRX 2.0 test programs makefile for Turbo C. Uses Turbo C make.
#
.AUTODEPEND

!include "../makedefs.bcc"

INCDIR= -I../include -I$(BCCROOT)\include
LIBDIR= -L$(BCCROOT)/lib

GRX20ST = ../lib/$(GRX_LIB_SUBDIR)/grx20$(MODEL).lib

PROGS=                  \
	arctest.exe     \
	blittest.exe    \
	circtest.exe    \
	cliptest.exe    \
	colorops.exe    \
	curstest.exe    \
	fontdemo.exe    \
	fonttest.exe    \
	imgtest.exe     \
	life.exe        \
	linetest.exe    \
	mousetst.exe    \
	pcirctst.exe    \
	pnmtest.exe     \
	polytest.exe    \
	rgbtest.exe     \
	sbctest.exe     \
	scroltst.exe    \
	spdtst16.exe    \
	textpatt.exe    \
	winclip.exe     \
	wintest.exe

all:    $(PROGS)

clean:
	if exist *.obj del *.obj
	if exist *.exe del *.exe

spdtst16.exe: speedtst.obj
	$(BCC) $(LIBDIR) $(LDOPT) -n. -espdtst16 speedtst.obj $(GRX20ST)

.obj.exe:
	$(BCC) $(LIBDIR) $(LDOPT) -n. -e$* $*.obj $(GRX20ST)

.c.obj:
	$(BCC) -c $(CCOPT) $(INCDIR) -o$*.obj $*.c

