## Aux -*- Makefile -*- for djgpp

prefix := $(DJDIR)
libdir := $(prefix)/lib
includedir := $(prefix)/include

EXE := .exe
EXAMPLELIBS := -lpng -lz -lalleg

#--------------------------------------------------
.PHONY: install

install: $(LIB)
	copy loadpng.h $(subst /,\,$(includedir))
	copy $(LIB) $(subst /,\,$(libdir))
